services:
  mysql:
    image: mysql:9.0.0
    build: docker/mysql
    container_name: mysql-container
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/data/application/init.sql
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    networks:
      - app-network

  php:
    image: php:8.3-apache
    build: docker/php
    container_name: php-container
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/tourbinou/public
    ports:
      - "8000:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  node:
    image: node:18
    container_name: node-container
    working_dir: /var/www/html/tourbinou
    volumes:
      - ./tourbinou:/var/www/html/tourbinou
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: bash -c "cd /var/www/html/tourbinou && npm install && npm run build"
  composer:
    image: composer:latest
    container_name: composer-container
    working_dir: /var/www/html/tourbinou
    volumes:
      - ./tourbinou:/var/www/html/tourbinou
      - composer_home:/tmp/composer  # Store global installs here
    environment:
      COMPOSER_HOME: /tmp/composer   # Redirect global installs
    depends_on:
      - php
    networks:
      - app-network
    command: bash -c "cd /var/www/html/tourbinou && composer install"
networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  composer_home:
